### ISSUE TITLE
ParameterizePlz: Position=0 to make Wildcards working

### ISSUE THREAD

**Issue by danubie** [IISResetMe/PSPresentations#1]
Hi Mathias,

thanks for your yesterdays session. I really love the "script to pipeline" development.
To make the Update-XmlFile_v9.ps1 and wildcard working it needs  
```
[Parameter(ValueFromPipeline = $true, ParameterSetName = 'ByPath', Position=0)]
```
Regards,
Wolfgang

**Comment by IISResetMe** [comment]
Excellent observation @danubie! I will update the last sample 🙂
